server:
  port: 8082

url: https://gridforecast.com/api/v1/forecast/
dateTimeAndToken: /202111131200?api_token=gPNf9QeGSArkACoK

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    password: yakushik
    username: yakushik
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: yakushik
#    password: yakushik
#    url: jdbc:postgresql://localhost:5432/postgres